import { 
    FaReact,
    FaJava,
    FaPython,
    FaAngular,
    FaMeteor,
    FaHtml5,
    FaCss3,
    FaPhp,
    FaSymfony,
    FaLaravel,
    FaRust,
    FaDocker,
    FaGit,
    FaGithub,
    FaBitbucket,
    FaGitlab,
    FaJenkins,
    FaSketch,
    FaFigma,
    FaAws,
    FaGoogle, 
    FaRunning,
    FaBootstrap,
    FaBookOpen,
    FaHandshake,
    FaMarkdown,
    FaLinux,
    FaWindows,
    FaHammer,
 } from "react-icons/fa";
import { 
    SiTypescript,
    SiSpring,
    SiFastapi,
    SiHibernate,
    SiSpringboot,
    SiSpringsecurity,
    SiCelery,
    SiFlask,
    SiExpress,
    SiRedux,
    SiKubernetes,
    SiGithubactions,
    SiTerraform,
    SiAnsible,
    SiJunit5,
    SiPytest,
    SiMockserviceworker,
    SiJest,
    SiMocha,
    SiJasmine,
    SiSonarqube,
    SiCucumber,
    SiSelenium,
    SiCypress,
    SiJira,
    SiPandas,
    SiNumpy,
    SiApachekafka,
    SiApachehadoop,
    SiScikitlearn,
    SiTensorflow,
    SiPytorch,
    SiApachespark,
    SiOwasp,
    SiOpenapiinitiative,
    SiScala,
    SiAdobe,
    SiPostman,
    SiLatex,
    SiSphinx,
    SiUml,
    SiLucid,
    SiSwagger,
} from "react-icons/si";
import { IoLogoJavascript } from "react-icons/io5";
import { 
    DiMongodb,
    DiDjango,
    DiMysql,
    DiPostgresql,
    DiRuby
 } from "react-icons/di";
import { MdOutlineViewKanban, MdOutlinePhone } from "react-icons/md";
import { FaBusinessTime, FaGolang, FaC, FaScrewdriverWrench, FaCompassDrafting, FaPersonDigging } from "react-icons/fa6";
import { GiThink, GiTeacher, GiStrongMan } from "react-icons/gi";
import { TbMath } from "react-icons/tb";
import { RiMentalHealthFill, RiNextjsFill, RiParentFill, RiPresentationLine, RiTailwindCssFill } from "react-icons/ri";
import { FcCollaboration } from "react-icons/fc";
import { PiStudent, PiFileCpp } from "react-icons/pi";
import { VscAzure } from "react-icons/vsc";
import { IconType } from 'react-icons';



export const iconMap: Record<string, IconType> = {
    "Java": FaJava,
    "Python": FaPython,
    "Typescript": SiTypescript,
    "FastAPI": SiFastapi,
    "JavaScript": IoLogoJavascript,
    "Next.js": RiNextjsFill,
    "React": FaReact,
    "Angular": FaAngular,
    "Meteor": FaMeteor,
    "HTML": FaHtml5,
    "CSS": FaCss3,
    "PHP": FaPhp,
    "Laravel": FaLaravel,
    "Symfony": FaSymfony,
    "C": FaC,
    "C++": PiFileCpp,
    "Go": FaGolang,
    "Rust": FaRust,
    "MySQL": DiMysql,
    "PostgreSQL": DiPostgresql,
    "MongoDB": DiMongodb,
    "Ruby": DiRuby,
    "Spring": SiSpring,
    "Spring Boot": SiSpringboot,
    "Spring Security": SiSpringsecurity,
    "Hibernate": SiHibernate,
    "Celery": SiCelery,
    "Django": DiDjango,
    "Flask": SiFlask,
    "Express": SiExpress,
    "Scala": SiScala,
    "Redux": SiRedux,
    "Bootstrap": FaBootstrap,
    "Tailwind": RiTailwindCssFill,
    "Figma": FaFigma,
    "AdobeXD": SiAdobe,
    "Sketch": FaSketch,
    "Docker": FaDocker,
    "Kubernetes": SiKubernetes,
    "Jenkins": FaJenkins,
    "Gitlab": FaGitlab,
    "Github": FaGithub,
    "Bitbucket": FaBitbucket,
    "Github Actions": SiGithubactions,
    "AWS": FaAws,
    "Azure": VscAzure,
    "GCP": FaGoogle,
    "Terraform": SiTerraform,
    "Ansible": SiAnsible,
    "Junit5": SiJunit5,
    "Pytest": SiPytest,
    "Mockserviceworker": SiMockserviceworker,
    "Jest": SiJest,
    "Mocha": SiMocha,
    "Jasmine": SiJasmine,
    "Selenium": SiSelenium,
    "Cypress": SiCypress,
    "Sonarqube": SiSonarqube,
    "Cucumber": SiCucumber,
    "Owasp": SiOwasp,
    "Git": FaGit,
    "Kanban": MdOutlineViewKanban,
    "Jira": SiJira,
    "Pandas": SiPandas,
    "Numpy": SiNumpy,
    "Kafka": SiApachekafka,
    "Spark": SiApachespark,
    "Hadoop": SiApachehadoop,
    "Scikit-learn": SiScikitlearn,
    "Tensorflow": SiTensorflow,
    "Pytorch": SiPytorch,
    "Swagger": SiSwagger,
    "Postman": SiPostman,
    "Open API": SiOpenapiinitiative,
    "Markdown": FaMarkdown,
    "Latex": SiLatex,
    "Sphinx": SiSphinx,
    "Uml": SiUml,
    "Lucid": SiLucid,
    "Linux": FaLinux,
    "Windows": FaWindows,
    "Problem Solving": TbMath,
    "Critical Thinking": GiThink,
    "Communication": MdOutlinePhone,
    "Presentation": RiPresentationLine,
    "Leadership": GiTeacher,
    "Mentorship": RiParentFill,
    "Adaptability": RiMentalHealthFill,
    "Resilience": GiStrongMan,
    "TimeManagement": FaBusinessTime,
    "Motivation": FaRunning,
    "Team Collaboration": FcCollaboration,
    "Conflict Resolution": FaHandshake,
    "Continuous Learning": FaBookOpen,
    "Professional Development": PiStudent,
    "Hammer": FaHammer,
    "Screwdriver Wrench": FaScrewdriverWrench,
    "Compass Drafting": FaCompassDrafting,
    "Person Digging": FaPersonDigging,
}

export function getFontAwesomeIcon(iconName: string): IconType | null {
    return iconMap[iconName] ?? null;
}