import { 
    FaReact,
    FaJava,
    FaPython,
    FaAngular,
    FaMeteor,
    FaHtml5,
    FaCss3,
    FaPhp,
    FaSymfony,
    FaLaravel,
    FaRust,
    FaDocker,
    FaGit,
    FaGithub,
    FaBitbucket,
    FaGitlab,
    FaJenkins,
    FaSketch,
    FaFigma,
    FaAws,
    FaGoogle, 
    FaRunning,
    FaBootstrap,
    FaBookOpen,
    FaHandshake,
    FaMarkdown,
    FaLinux,
    FaWindows,
 } from "react-icons/fa";
import { 
    SiTypescript,
    SiSpring,
    SiFastapi,
    SiHibernate,
    SiSpringboot,
    SiSpringsecurity,
    SiCelery,
    SiFlask,
    SiExpress,
    SiRedux,
    SiKubernetes,
    SiGithubactions,
    SiTerraform,
    SiAnsible,
    SiJunit5,
    SiPytest,
    SiMockserviceworker,
    SiJest,
    SiMocha,
    SiJasmine,
    SiSonarqube,
    SiCucumber,
    SiSelenium,
    SiCypress,
    SiJira,
    SiPandas,
    SiNumpy,
    SiApachekafka,
    SiApachehadoop,
    SiScikitlearn,
    SiTensorflow,
    SiPytorch,
    SiApachespark,
    SiOwasp,
    SiOpenapiinitiative,
    SiScala,
    SiAdobe,
    SiPostman,
    SiLatex,
    SiSphinx,
    SiUml,
    SiLucid,
    SiAsciidoctor,
    SiSwagger,
} from "react-icons/si";
import { IoLogoJavascript } from "react-icons/io5";
import { 
    DiMongodb,
    DiDjango,
    DiMysql,
    DiPostgresql,
    DiRuby
 } from "react-icons/di";
import { MdOutlineViewKanban, MdOutlinePhone } from "react-icons/md";
import { FaBusinessTime, FaGolang, FaC } from "react-icons/fa6";
import { GiThink, GiTeacher, GiStrongMan } from "react-icons/gi";
import { TbMath } from "react-icons/tb";
import { RiMentalHealthFill, RiNextjsFill, RiParentFill, RiPresentationLine, RiTailwindCssFill } from "react-icons/ri";
import { FcCollaboration } from "react-icons/fc";
import { PiStudent, PiFileCpp } from "react-icons/pi";
import { VscAzure } from "react-icons/vsc";
import { IconType } from 'react-icons';



export const iconMap: Record<string, IconType> = {
    "FaJava": FaJava,
    "FaPython": FaPython,
    "SiTypescript": SiTypescript,
    "SiFastapi": SiFastapi,
    "IoLogoJavascript": IoLogoJavascript,
    "RiNextjsFill": RiNextjsFill,
    "FaReact": FaReact,
    "FaAngular": FaAngular,
    "FaMeteor": FaMeteor,
    "FaHtml5": FaHtml5,
    "FaCss3": FaCss3,
    "FaPhp": FaPhp,
    "FaLaravel": FaLaravel,
    "FaSymfony": FaSymfony,
    "FaC": FaC,
    "PiFileCpp": PiFileCpp,
    "FaGolang": FaGolang,
    "FaRust": FaRust,
    "DiMysql": DiMysql,
    "DiPostgresql": DiPostgresql,
    "DiMongodb": DiMongodb,
    "DiRuby": DiRuby,
    "SiSpring": SiSpring,
    "SiSpringboot": SiSpringboot,
    "SiSpringsecurity": SiSpringsecurity,
    "SiHibernate": SiHibernate,
    "SiCelery": SiCelery,
    "DiDjango": DiDjango,
    "SiFlask": SiFlask,
    "SiExpress": SiExpress,
    "SiScala": SiScala,
    "SiRedux": SiRedux,
    "FaBootstrap": FaBootstrap,
    "RiTailwindCssFill": RiTailwindCssFill,
    "FaFigma": FaFigma,
    "SiAdobe": SiAdobe,
    "FaSketch": FaSketch,
    "FaDocker": FaDocker,
    "SiKubernetes": SiKubernetes,
    "FaJenkins": FaJenkins,
    "FaGitlab": FaGitlab,
    "FaGithub": FaGithub,
    "FaBitbucket": FaBitbucket,
    "SiGithubactions": SiGithubactions,
    "FaAws": FaAws,
    "VscAzure": VscAzure,
    "FaGoogle": FaGoogle,
    "SiTerraform": SiTerraform,
    "SiAnsible": SiAnsible,
    "SiJunit5": SiJunit5,
    "SiPytest": SiPytest,
    "SiMockserviceworker": SiMockserviceworker,
    "SiJest": SiJest,
    "SiMocha": SiMocha,
    "SiJasmine": SiJasmine,
    "SiSelenium": SiSelenium,
    "SiCypress": SiCypress,
    "SiSonarqube": SiSonarqube,
    "SiCucumber": SiCucumber,
    "SiOwasp": SiOwasp,
    "FaGit": FaGit,
    "MdOutlineViewKanban": MdOutlineViewKanban,
    "SiJira": SiJira,
    "SiPandas": SiPandas,
    "SiNumpy": SiNumpy,
    "SiApachekafka": SiApachekafka,
    "SiApachespark": SiApachespark,
    "SiApachehadoop": SiApachehadoop,
    "SiScikitlearn": SiScikitlearn,
    "SiTensorflow": SiTensorflow,
    "SiPytorch": SiPytorch,
    "SiSwagger": SiSwagger,
    "SiPostman": SiPostman,
    "SiOpenapiinitiative": SiOpenapiinitiative,
    "FaMarkdown": FaMarkdown,
    "SiAsciidoctor": SiAsciidoctor,
    "SiLatex": SiLatex,
    "SiSphinx": SiSphinx,
    "SiUml": SiUml,
    "SiLucid": SiLucid,
    "FaLinux": FaLinux,
    "FaWindows": FaWindows,
    "GiThink": GiThink,
    "GiTeacher": GiTeacher,
    "MdOutlinePhone": MdOutlinePhone,
    "RiPresentationLine": RiPresentationLine,
    "RiParentFill": RiParentFill,
    "GiStrongMan": GiStrongMan,
    "FaBusinessTime": FaBusinessTime,
    "FaRunning": FaRunning,
    "FcCollaboration": FcCollaboration,
    "FaHandshake": FaHandshake,
    "FaBookOpen": FaBookOpen,
    "PiStudent": PiStudent,
    "TbMath": TbMath,
    "RiMentalHealthFill": RiMentalHealthFill,
}

export function getFontAwesomeIcon(iconName: string): IconType | null {
    return iconMap[iconName] ?? null;
}